-- Historical compatibility note
--
-- Do not redefine transition_booking from this dashboard repository. The
-- previous version of this file rejected transition_booking(..., 'accept', ...)
-- and would restore the payment-first deadlock if it were run again.
--
-- The canonical implementation now lives in the Flutter/Supabase repository:
--
--   supabase/migrations/
--   20260730125530_booking_acceptance_cash_receipts_and_visa_progress.sql
--
-- That migration includes both requirements:
--   1. a company must accept a requested booking before cash confirmation;
--      FIB payment can be recorded before acceptance but cannot confirm alone;
--   2. transition_booking(..., 'ready', ...) still requires every traveller's
--      visa_status to be approved.
--
-- This file intentionally performs no database mutation.
